In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('StudP.csv')

In [3]:
df

,Gender,Age,Semester,Branch,Difficulty_Level,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level,Sleep_Hours_per_Night,Final_Score,Grade,Pass/Fail
0,Male,25,7,ME,Hard,83.119601,43.602889,57.313551,61.267100,2.189965,26.554882,13.113085,Yes,NaN,Mid,4.360995,6.643720,42.537587,D,Pass
1,Female,26,8,CSE,Hard,80.146477,46.570204,77.295058,64.963550,NaN,20.097328,23.047135,Yes,Primary,Mid,4.577771,9.000000,50.717225,C,Pass
2,Female,21,4,CSE,Moderate,47.776656,50.788649,91.277407,82.465026,4.317889,18.284042,NaN,No,Primary,Low,2.643731,7.425057,58.440447,C,Pass
3,Male,20,2,ME,Easy,70.245418,47.505302,74.334697,44.884179,NaN,14.656669,12.339114,Yes,Primary,NaN,3.178601,8.100680,57.425304,C,Pass
4,Male,22,5,ECE,Moderate,92.457907,80.381252,100.000000,65.223913,4.450505,20.285765,12.661000,Yes,Secondary,Mid,4.854659,7.780219,72.651823,A,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,20,2,Civil,Easy,71.866994,53.181259,71.683076,71.009105,5.720281,16.237270,15.236351,Yes,Graduate,High,7.696242,8.596510,51.886448,C,Pass
9996,Female,24,6,ME,Hard,68.498687,78.392884,94.855883,63.662170,6.418717,21.081963,25.719023,Yes,Secondary,Low,6.977332,8.853728,54.605373,C,Pass
9997,Female,19,2,CSE,Easy,NaN,77.670475,88.046592,51.059314,10.000000,10.534530,1.997118,Yes,Graduate,Low,4.620197,6.372061,63.066394,B,Pass
9998,Male,26,8,ECE,Hard,62.939364,39.764761,76.620477,70.689797,6.620119,21.302122,20.028521,Yes,Secondary,Mid,7.791529,5.788218,41.705236,D,Pass
9999,Male,25,7,CSE,Hard,68.027305,80.245295,58.729781,92.769061,3.934203,23.060698,5.006513,Yes,Postgraduate,NaN,3.722440,5.764017,64.552063,B,Pass

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   10000 non-null  object
 1   Age                      10000 non-null  int64
 2   Semester                 10000 non-null  int64
 3   Branch                   10000 non-null  object
 4   Difficulty_Level         10000 non-null  object
 5   Attendance (%)           9146 non-null   float64
 6   Midterm_Score            10000 non-null  float64
 7   Assignments_Avg          10000 non-null  float64
 8   Quizzes_Avg              10000 non-null  float64
 9   Participation_Score      9106 non-null   float64
 10  Projects_Score           10000 non-null  float64
 11  Study_Hours_per_Week     8793 non-null   float64
 12  Internet_Access_at_Home  10000 non-null  object
 13  Parent_Education_Level   7995 non-null   object
 14  Family_Income_Level      8516 non-null   object
 15  Stress_Level             10000 non-null  float64
 16  Sleep_Hours_per_Night    10000 non-null  float64
 17  Final_Score              10000 non-null  float64
 18  Grade                    10000 non-null  object
 19  Pass/Fail                10000 non-null  object
dtypes: float64(10), int64(2), object(8)
memory usage: 1.5+ MB

In [5]:
df.describe()

,Age,Semester,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Stress_Level,Sleep_Hours_per_Night,Final_Score
count,10000.000000,10000.000000,9146.000000,10000.000000,10000.000000,10000.000000,9106.000000,10000.000000,8793.000000,10000.000000,10000.000000,10000.000000
mean,22.042400,4.540900,75.086273,64.889480,70.021602,68.061132,5.976638,19.972879,15.250086,5.003915,6.798897,54.501562
std,2.353074,2.301707,14.135381,14.838878,11.818102,13.889152,1.940925,4.939312,7.828188,1.940182,1.163283,10.397563
min,18.000000,1.000000,23.679306,20.000000,30.000000,20.000000,1.000000,5.000000,0.000000,1.000000,4.000000,16.497156
25%,20.000000,3.000000,65.327423,54.802866,62.156808,58.711988,4.651005,16.537123,9.628410,3.649447,6.020395,47.967779
50%,22.000000,5.000000,75.259900,64.896744,70.068992,68.180154,5.984960,19.990199,15.223497,4.975828,6.810205,54.968131
75%,24.000000,7.000000,85.385109,75.061188,78.115986,77.428597,7.308829,23.463102,20.582567,6.327369,7.616802,61.544538
max,26.000000,8.000000,100.000000,100.000000,100.000000,100.000000,10.000000,30.000000,42.960906,10.000000,9.000000,85.000000

In [6]:
# Correct - use & between conditions, and wrap each condition in parentheses
df_filtered = df[(df['Final_Score'] > 70) & (df['Final_Score'] < 80)]

In [7]:
df["Grade"].value_counts()

Grade
C    3828
B    2511
D    2357
F     787
A     436
E      81
Name: count, dtype: int64

In [8]:
if (df['Final_Score'] >= 70).any():
    df.loc[df['Final_Score'] >= 70, 'Final_Score'] = df['Final_Score'] + 11

In [9]:
def calculate_grade(score):
    if pd.isna(score):
        return 'Unknown'
    if score >= 90:
        return 'O'
    elif score >= 80:
        return 'E'
    elif score >= 70:
        return 'A'
    elif score >= 60:
        return 'B'
    elif score >= 50:
        return 'C'
    elif score >= 40:
        return 'D'
    else:
        return 'F'


df['Grade'] = df['Final_Score'].apply(calculate_grade)

In [10]:
df["Grade"].value_counts()

Grade
C    3828
B    2511
D    2357
F     787
E     432
O      85
Name: count, dtype: int64

In [11]:
df.loc[(df['Final_Score'] >= 58) & (df['Final_Score'] < 91), 'Final_Score'] += 2

In [12]:
df['Grade'] = df['Final_Score'].apply(calculate_grade)

In [13]:
df["Grade"].value_counts()

Grade
C    3073
B    2956
D    2357
F     787
E     407
A     310
O     110
Name: count, dtype: int64

In [14]:
df.loc[(df['Final_Score'] >= 58) & (df['Final_Score'] < 91), 'Final_Score'] += 3

In [15]:
df['Grade'] = df['Final_Score'].apply(calculate_grade)

In [16]:
df["Grade"].value_counts()

Grade
C    3073
D    2357
B    2317
A     949
F     787
E     319
O     198
Name: count, dtype: int64

In [17]:
df.loc[(df['Final_Score'] >= 58) & (df['Final_Score'] < 91), 'Final_Score'] += 2

In [18]:
df['Grade'] = df['Final_Score'].apply(calculate_grade)

In [19]:
df["Grade"].value_counts()

Grade
C    3073
D    2357
B    1755
A    1511
F     787
O     313
E     204
Name: count, dtype: int64

In [20]:
df.loc[(df['Final_Score'] >= 58) & (df['Final_Score'] < 81), 'Final_Score'] += 2

In [21]:
df['Grade'] = df['Final_Score'].apply(calculate_grade)

In [22]:
df["Grade"].value_counts()

Grade
C    3073
D    2357
A    2154
B    1112
F     787
O     313
E     204
Name: count, dtype: int64

In [23]:
df.loc[(df['Final_Score'] >= 58) & (df['Final_Score'] < 81), 'Final_Score'] += 2
df['Grade'] = df['Final_Score'].apply(calculate_grade)
df["Grade"].value_counts()

Grade
C    3073
A    2755
D    2357
F     787
B     368
E     347
O     313
Name: count, dtype: int64

In [24]:
df.loc[(df['Final_Score'] >= 58) & (df['Final_Score'] < 81), 'Final_Score'] += 2
df['Grade'] = df['Final_Score'].apply(calculate_grade)
df["Grade"].value_counts()

Grade
C    3073
A    2747
D    2357
F     787
E     723
O     313
Name: count, dtype: int64

In [27]:
df[df['Final_Score']>=90]

,Gender,Age,Semester,Branch,Difficulty_Level,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level,Sleep_Hours_per_Night,Final_Score,Grade,Pass/Fail
4,Male,22,5,ECE,Moderate,92.457907,80.381252,100.000000,65.223913,4.450505,20.285765,12.661000,Yes,Secondary,Mid,4.854659,7.780219,90.651823,O,Pass
12,Female,18,1,CSE,Easy,85.273624,78.650818,60.367484,77.767524,8.463095,17.085678,19.189322,No,Graduate,Mid,5.995108,5.075500,92.072234,O,Pass
81,Male,18,1,ECE,Easy,80.708321,64.138411,74.258496,75.996448,5.280065,27.512011,NaN,No,Secondary,NaN,3.668990,6.385400,91.208335,O,Pass
110,Male,20,2,Civil,Easy,80.227981,92.754724,90.039832,61.965977,2.416007,19.951978,15.700027,Yes,Secondary,Low,5.459545,7.683759,90.052461,O,Pass
132,Male,23,6,ME,Hard,62.781625,99.512123,77.131030,65.635771,5.555490,21.314043,22.015105,No,Postgraduate,Mid,5.124153,6.327561,90.853090,O,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9860,Female,23,6,CSE,Hard,94.940354,50.242313,74.941478,72.749149,9.835714,14.873027,11.124266,Yes,Secondary,High,4.821818,5.813219,96.000000,O,Pass
9863,Female,19,2,CSE,Easy,77.073368,67.040885,72.670278,75.394794,7.452090,26.292208,20.390391,Yes,Graduate,Low,5.636951,5.280497,92.692582,O,Pass
9968,Female,19,1,CSE,Easy,59.679924,50.349244,73.166707,83.059753,4.951446,12.454239,23.148337,Yes,Secondary,Low,6.607173,6.140779,96.000000,O,Pass
9984,Female,20,3,CSE,Moderate,100.000000,56.092913,94.353499,62.826409,6.231890,27.385555,25.710639,Yes,Graduate,Mid,2.311724,6.050028,90.309750,O,Pass
9993,Female,19,2,CSE,Easy,76.035911,94.066560,49.596655,50.274963,NaN,21.612209,25.831670,Yes,NaN,NaN,5.751259,8.489328,92.851870,O,Pass

In [28]:
df.loc[(df['Final_Score'] >= 58) & (df['Final_Score'] < 95), 'Final_Score'] += 2
df['Grade'] = df['Final_Score'].apply(calculate_grade)
df["Grade"].value_counts()

Grade
C    3073
D    2357
A    2317
E     949
F     787
O     517
Name: count, dtype: int64

In [29]:
df.describe()

,Age,Semester,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Stress_Level,Sleep_Hours_per_Night,Final_Score
count,10000.000000,10000.000000,9146.000000,10000.000000,10000.000000,10000.000000,9106.000000,10000.000000,8793.000000,10000.000000,10000.000000,10000.000000
mean,22.042400,4.540900,75.086273,64.889480,70.021602,68.061132,5.976638,19.972879,15.250086,5.003915,6.798897,60.342162
std,2.353074,2.301707,14.135381,14.838878,11.818102,13.889152,1.940925,4.939312,7.828188,1.940182,1.163283,16.883737
min,18.000000,1.000000,23.679306,20.000000,30.000000,20.000000,1.000000,5.000000,0.000000,1.000000,4.000000,16.497156
25%,20.000000,3.000000,65.327423,54.802866,62.156808,58.711988,4.651005,16.537123,9.628410,3.649447,6.020395,47.967779
50%,22.000000,5.000000,75.259900,64.896744,70.068992,68.180154,5.984960,19.990199,15.223497,4.975828,6.810205,54.968131
75%,24.000000,7.000000,85.385109,75.061188,78.115986,77.428597,7.308829,23.463102,20.582567,6.327369,7.616802,76.544538
max,26.000000,8.000000,100.000000,100.000000,100.000000,100.000000,10.000000,30.000000,42.960906,10.000000,9.000000,96.097902

In [30]:
df.to_csv('student_data.csv', index=False)

In [5]:
import pandas as pd
df = pd.read_csv("student_data1.csv")
bins = [0, 40, 50, 60, 70, 80, 90, 100]
labels = ["0-39", "40-49", "50-59", "60-69", "70-79", "80-89", "90-100"]

df["Score_Range"] = pd.cut(
    df["Final_Score"],
    bins=bins,
    labels=labels,
    right=True,          # include right side
    include_lowest=True
)

print(df["Score_Range"].value_counts().sort_index())

Score_Range
0-39      1914
40-49     1534
50-59     1988
60-69     2157
70-79     1593
80-89      641
90-100     173
Name: count, dtype: int64

In [6]:
df.describe()

,Age,Semester,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Stress_Level,Sleep_Hours_per_Night,Final_Score
count,10000.000000,10000.000000,9397.000000,10000.000000,10000.000000,10000.000000,9131.000000,10000.000000,9197.000000,10000.000000,10000.000000,10000.000000
mean,21.283700,4.155200,65.323773,50.999104,52.477626,42.422031,5.177750,43.786808,20.930463,5.707245,7.285390,56.494233
std,2.478191,2.226254,11.410746,16.366411,16.131862,14.601556,1.896645,14.762405,5.999391,1.947752,0.983288,17.725346
min,18.000000,1.000000,23.161495,20.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,4.000000,0.000000
25%,19.000000,2.000000,57.753435,38.980000,41.627500,32.457500,3.852329,33.990000,16.893976,4.350000,6.630000,44.117500
50%,21.000000,4.000000,65.678707,52.135000,53.590000,42.995000,5.195632,44.490000,21.128849,5.720000,7.280000,57.980000
75%,23.000000,6.000000,73.319787,63.072500,64.102500,52.500000,6.504112,54.230000,25.114540,7.060000,7.960000,69.480000
max,28.000000,8.000000,100.000000,100.000000,100.000000,91.390000,10.000000,92.100000,40.000000,10.000000,10.000000,100.000000

In [9]:
if (df['Final_Score']<90).any(): 
    df['Final_Score'] = df['Final_Score'] + 2

In [10]:
df["Score_Range"] = pd.cut(
    df["Final_Score"],
    bins=bins,
    labels=labels,
    right=True,          # include right side
    include_lowest=True
)

print(df["Score_Range"].value_counts().sort_index())

Score_Range
0-39      1667
40-49     1470
50-59     1870
60-69     2172
70-79     1781
80-89      800
90-100     212
Name: count, dtype: int64

In [12]:
if (df['Final_Score']<90).any(): 
    df['Final_Score'] = df['Final_Score'] + 2

In [13]:
df["Score_Range"] = pd.cut(
    df["Final_Score"],
    bins=bins,
    labels=labels,
    right=True,          # include right side
    include_lowest=True
)

print(df["Score_Range"].value_counts().sort_index())

Score_Range
0-39      1445
40-49     1361
50-59     1781
60-69     2144
70-79     1933
80-89     1005
90-100     284
Name: count, dtype: int64

In [14]:
if (df['Final_Score']<90).any(): 
    df['Final_Score'] = df['Final_Score'] + 2

In [15]:
df["Score_Range"] = pd.cut(
    df["Final_Score"],
    bins=bins,
    labels=labels,
    right=True,          # include right side
    include_lowest=True
)

print(df["Score_Range"].value_counts().sort_index())

Score_Range
0-39      1255
40-49     1231
50-59     1712
60-69     2111
70-79     2010
80-89     1229
90-100     373
Name: count, dtype: int64

In [16]:
def calculate_grade(score):
    if pd.isna(score):
        return 'Unknown'
    if score >= 90:
        return 'O'
    elif score >= 80:
        return 'E'
    elif score >= 70:
        return 'A'
    elif score >= 60:
        return 'B'
    elif score >= 50:
        return 'C'
    elif score >= 40:
        return 'D'
    else:
        return 'F'


df['Grade'] = df['Final_Score'].apply(calculate_grade)

In [17]:
df["Grade"].value_counts()

Grade
B    2109
A    2014
C    1712
F    1253
E    1230
D    1230
O     452
Name: count, dtype: int64

In [20]:
df[df['Final_Score']>=90].value_counts().sum()

np.int64(193)

In [21]:
print(">= 90 :", (df["Final_Score"] >= 90).sum())

>= 90 : 452

In [22]:
print(">= 90 :", (df["Final_Score"] >= 90).sum())
print(">= 80 :", (df["Final_Score"] >= 80).sum())
print(">= 70 :", (df["Final_Score"] >= 70).sum())
print(">= 60 :", (df["Final_Score"] >= 60).sum())
print(">= 50 :", (df["Final_Score"] >= 50).sum())
print("< 50  :", (df["Final_Score"] < 50).sum())

>= 90 : 452
>= 80 : 1682
>= 70 : 3696
>= 60 : 5805
>= 50 : 7517
< 50  : 2483

In [24]:
df = pd.read_csv('Student_data1.csv')

In [27]:
print("90-100 :", ((df["Final_Score"] >= 90) & (df["Final_Score"] <= 100)).sum())
print("80-89  :", ((df["Final_Score"] >= 80) & (df["Final_Score"] < 90)).sum())
print("70-79  :", ((df["Final_Score"] >= 70) & (df["Final_Score"] < 80)).sum())
print("60-69  :", ((df["Final_Score"] >= 60) & (df["Final_Score"] < 70)).sum())
print("50-59  :", ((df["Final_Score"] >= 50) & (df["Final_Score"] < 60)).sum())
print("40-49  :", ((df["Final_Score"] >= 40) & (df["Final_Score"] < 50)).sum())
print("< 40   :", (df["Final_Score"] < 40).sum())

90-100 : 173
80-89  : 644
70-79  : 1594
60-69  : 2157
50-59  : 1984
40-49  : 1534
< 40   : 1914

In [28]:
df.loc[df['Final_Score'] < 90, 'Final_Score'] += 2

In [29]:
print("90-100 :", ((df["Final_Score"] >= 90) & (df["Final_Score"] <= 100)).sum())
print("80-89  :", ((df["Final_Score"] >= 80) & (df["Final_Score"] < 90)).sum())
print("70-79  :", ((df["Final_Score"] >= 70) & (df["Final_Score"] < 80)).sum())
print("60-69  :", ((df["Final_Score"] >= 60) & (df["Final_Score"] < 70)).sum())
print("50-59  :", ((df["Final_Score"] >= 50) & (df["Final_Score"] < 60)).sum())
print("40-49  :", ((df["Final_Score"] >= 40) & (df["Final_Score"] < 50)).sum())
print("< 40   :", (df["Final_Score"] < 40).sum())

90-100 : 241
80-89  : 799
70-79  : 1784
60-69  : 2172
50-59  : 1870
40-49  : 1467
< 40   : 1667

In [30]:
df.loc[df['Final_Score'] < 90, 'Final_Score'] += 2

In [31]:
print("90-100 :", ((df["Final_Score"] >= 90) & (df["Final_Score"] <= 100)).sum())
print("80-89  :", ((df["Final_Score"] >= 80) & (df["Final_Score"] < 90)).sum())
print("70-79  :", ((df["Final_Score"] >= 70) & (df["Final_Score"] < 80)).sum())
print("60-69  :", ((df["Final_Score"] >= 60) & (df["Final_Score"] < 70)).sum())
print("50-59  :", ((df["Final_Score"] >= 50) & (df["Final_Score"] < 60)).sum())
print("40-49  :", ((df["Final_Score"] >= 40) & (df["Final_Score"] < 50)).sum())
print("< 40   :", (df["Final_Score"] < 40).sum())

90-100 : 332
80-89  : 1006
70-79  : 1933
60-69  : 2144
50-59  : 1779
40-49  : 1362
< 40   : 1444

In [32]:
import numpy as np

conditions = [
    df['Final_Score'] >= 90,
    df['Final_Score'] >= 80,
    df['Final_Score'] >= 70,
    df['Final_Score'] >= 60,
    df['Final_Score'] >= 50,
    df['Final_Score'] >= 40
]

grades = ['O', 'E', 'A', 'B', 'C', 'D']

df['Grade'] = np.select(conditions, grades, default='F')

print(df[['Final_Score','Grade']].head())

   Final_Score Grade
0        56.93     C
1        63.42     B
2        60.59     B
3        58.40     C
4        60.73     B

In [33]:
df['Grade'].value_counts()

Grade
B    2144
A    1933
C    1779
F    1444
D    1362
E    1006
O     332
Name: count, dtype: int64

In [34]:
df.to_csv('students_data.csv', index=False)

In [35]:
df1 = pd.read_csv("students_data.csv")

In [36]:
df['Grade'].value_counts()

Grade
B    2144
A    1933
C    1779
F    1444
D    1362
E    1006
O     332
Name: count, dtype: int64

In [44]:
df1[df1['Final_Score']==100]

,Gender,Age,Semester,Branch,Difficulty_Level,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level,Sleep_Hours_per_Night,Final_Score,Grade,Pass/Fail
121,Male,18,2,ECE,Easy,83.099327,82.38,84.88,71.01,5.710159,71.15,39.236963,No,Postgraduate,Mid,1.00,7.94,100.0,O,Pass
2457,Male,18,1,ECE,Easy,59.167144,95.78,85.45,58.09,NaN,72.03,30.514572,Yes,Secondary,Low,1.22,9.32,100.0,O,Pass
2664,Male,18,2,ECE,Easy,82.729879,93.91,77.01,46.38,6.696883,83.22,25.085156,Yes,Secondary,High,3.67,9.24,100.0,O,Pass
3080,Male,23,2,CSE,Easy,100.000000,83.27,83.18,57.15,6.649111,66.13,30.608291,Yes,Primary,Mid,1.00,8.64,100.0,O,Pass
3512,Male,19,1,Civil,Easy,81.165071,66.53,75.83,50.92,NaN,73.29,35.181572,Yes,Graduate,High,2.45,9.97,100.0,O,Pass
6604,Male,18,2,EEE,Easy,95.213828,88.43,84.30,56.31,NaN,53.25,33.845647,Yes,NaN,NaN,1.58,8.06,100.0,O,Pass
6629,Male,21,2,CSE,Easy,92.319642,94.00,77.45,69.15,7.835624,57.21,33.357379,Yes,NaN,Mid,4.93,7.78,100.0,O,Pass
7522,Male,19,1,ME,Easy,88.504586,97.14,78.74,61.80,6.789935,65.86,28.601728,Yes,Primary,Mid,2.92,8.46,100.0,O,Pass
7576,Female,19,1,ME,Easy,93.504474,86.31,69.66,62.97,8.756423,65.60,36.861832,Yes,Graduate,NaN,3.01,7.07,100.0,O,Pass
7662,Male,18,1,CSE,Easy,85.504458,93.34,81.57,50.12,7.653144,77.52,33.524451,No,Secondary,High,3.35,8.21,100.0,O,Pass
7747,Male,23,4,ECE,Easy,82.387430,93.08,75.40,83.68,8.741110,66.17,34.900123,Yes,Primary,Mid,4.08,7.79,100.0,O,Pass
7937,Male,19,1,EEE,Hard,75.672854,82.43,95.92,65.14,9.962912,77.24,35.838019,Yes,Secondary,Mid,6.28,7.20,100.0,O,Pass
8558,Male,21,6,EEE,Easy,96.972941,95.95,77.08,68.82,7.798418,65.25,35.926858,Yes,Postgraduate,High,1.52,8.86,100.0,O,Pass
9055,Male,23,7,ECE,Moderate,91.025833,84.39,71.77,59.99,9.985420,67.72,36.277533,Yes,Secondary,NaN,3.77,8.29,100.0,O,Pass
9213,Male,18,2,CSE,Moderate,85.864195,77.69,82.94,73.00,9.939649,55.44,32.294901,Yes,Graduate,Low,7.20,8.12,100.0,O,Pass
9964,Female,22,4,CSE,Moderate,85.915595,79.70,97.81,87.14,9.797990,72.17,37.800107,Yes,Secondary,High,4.31,8.31,100.0,O,Pass

In [45]:
df1['Assignments_Avg'] = df1['Assignments_Avg'] / 10
df1['Quizzes_Avg'] = df1['Quizzes_Avg'] / 10

In [46]:
df1.describe()

,Age,Semester,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Stress_Level,Sleep_Hours_per_Night,Final_Score
count,10000.000000,10000.000000,9397.000000,10000.000000,10000.000000,10000.000000,9131.000000,10000.000000,9197.000000,10000.000000,10000.000000,10000.000000
mean,21.283700,4.155200,65.323773,50.999104,5.247763,4.242203,5.177750,43.786808,20.930463,5.707245,7.285390,60.411433
std,2.478191,2.226254,11.410746,16.366411,1.613186,1.460156,1.896645,14.762405,5.999391,1.947752,0.983288,17.560981
min,18.000000,1.000000,23.161495,20.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,4.000000,4.000000
25%,19.000000,2.000000,57.753435,38.980000,4.162750,3.245750,3.852329,33.990000,16.893976,4.350000,6.630000,48.117500
50%,21.000000,4.000000,65.678707,52.135000,5.359000,4.299500,5.195632,44.490000,21.128849,5.720000,7.280000,61.980000
75%,23.000000,6.000000,73.319787,63.072500,6.410250,5.250000,6.504112,54.230000,25.114540,7.060000,7.960000,73.480000
max,28.000000,8.000000,100.000000,100.000000,10.000000,9.139000,10.000000,92.100000,40.000000,10.000000,10.000000,100.000000

In [50]:
df['Projects_Score'] = (df['Projects_Score'] / 100) * 20

In [51]:
df1.describe()

,Age,Semester,Attendance (%),Midterm_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Study_Hours_per_Week,Stress_Level,Sleep_Hours_per_Night,Final_Score
count,10000.000000,10000.000000,9397.000000,10000.000000,10000.000000,10000.000000,9131.000000,10000.000000,9197.000000,10000.000000,10000.000000,10000.000000
mean,21.283700,4.155200,65.323773,50.999104,5.247763,4.242203,5.177750,43.786808,20.930463,5.707245,7.285390,60.411433
std,2.478191,2.226254,11.410746,16.366411,1.613186,1.460156,1.896645,14.762405,5.999391,1.947752,0.983288,17.560981
min,18.000000,1.000000,23.161495,20.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,4.000000,4.000000
25%,19.000000,2.000000,57.753435,38.980000,4.162750,3.245750,3.852329,33.990000,16.893976,4.350000,6.630000,48.117500
50%,21.000000,4.000000,65.678707,52.135000,5.359000,4.299500,5.195632,44.490000,21.128849,5.720000,7.280000,61.980000
75%,23.000000,6.000000,73.319787,63.072500,6.410250,5.250000,6.504112,54.230000,25.114540,7.060000,7.960000,73.480000
max,28.000000,8.000000,100.000000,100.000000,10.000000,9.139000,10.000000,92.100000,40.000000,10.000000,10.000000,100.000000

In [53]:
print(df1.columns)

Index(['Gender', 'Age', 'Semester', 'Branch', 'Difficulty_Level',
       'Attendance (%)', 'Midterm_Score', 'Assignments_Avg', 'Quizzes_Avg',
       'Participation_Score', 'Projects_Score', 'Study_Hours_per_Week',
       'Internet_Access_at_Home', 'Parent_Education_Level',
       'Family_Income_Level', 'Stress_Level', 'Sleep_Hours_per_Night',
       'Final_Score', 'Grade', 'Pass/Fail'],
      dtype='object')

In [54]:
print(df1['Projects_Score'].describe())

count    10000.000000
mean        43.786808
std         14.762405
min          0.000000
25%         33.990000
50%         44.490000
75%         54.230000
max         92.100000
Name: Projects_Score, dtype: float64